theme="github_dark_high_contrast"

[editor]
bufferline = "multiple"
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
"$" = ["goto_line_end"]
0 = ["goto_line_start"]
B = ["move_prev_long_word_start", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"
E = ["move_next_long_word_end", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
esc = ["collapse_selection", "keep_primary_selection"]
G = "goto_file_end"
"}" = ["goto_next_paragraph", "collapse_selection"]
"{" = ["goto_prev_paragraph", "collapse_selection"]
"%" = ["match_brackets"]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]
O = ["open_above", "normal_mode"]
o = ["open_below", "normal_mode"]
u = ["undo", "collapse_selection"]
V = ["select_mode", "extend_to_line_bounds"]
W = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
w = ["move_next_word_start", "move_char_right", "collapse_selection"]
x = "delete_selection"

[keys.normal.d]
a = ["select_textobject_around"]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
g = { g = ["select_mode", "extend_to_line_bounds", "goto_file_start", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"] }
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
i = ["select_textobject_inner"]
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
s = ["surround_delete"]
t = ["extend_till_char"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal.space]
f = {s = [":w"]}
q = [":q"]
b = {q = [":buffer-close"]}


[keys.normal.y]
g = { g = ["select_mode", "extend_to_line_bounds", "goto_file_start", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"] }
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]

[keys.select]
"$" = "goto_line_end"
0 = "goto_line_start"
a = "select_textobject_around"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
G = "goto_file_end"
i = "select_textobject_inner"
j = ["extend_line_down", "extend_to_line_bounds"]
k = ["extend_line_up", "extend_to_line_bounds"]
"%" = "match_brackets"
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
