theme="github_dark_high_contrast"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
0 = ["goto_line_start"]
"$" = ["goto_line_end"]
"C-s" = [":w"]
G = "goto_file_end"
